version: "3.7"

services:
  ping:
    image: golang:1.13
    working_dir: /go/github.com/socialpoint/envoyproxy-envoy-issues-9922/services/ping
    volumes:
      - ./services/ping:/go/github.com/socialpoint/envoyproxy-envoy-issues-9922/services/ping
    expose:
      - "10005"
    command: go run main.go

  envoy-v1-12-0:
    image: envoyproxy/envoy:v1.12.0
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  envoy-v1-12-1:
    image: envoyproxy/envoy:v1.12.1
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  envoy-v1-12-2:
    image: envoyproxy/envoy:v1.12.2
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  envoy-v1-12-3:
    image: envoyproxy/envoy:v1.12.3
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  envoy-v1-13-0:
    image: envoyproxy/envoy:v1.13.0
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  envoy-v1-13-1:
    image: envoyproxy/envoy:v1.13.1
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  envoy-v1-14-1:
    image: envoyproxy/envoy:v1.14.1
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  envoy-dev-latest:
    image: envoyproxy/envoy-dev:latest
    depends_on:
      - ping
    expose:
      - "10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  test:
    image: golang:1.13
    depends_on:
      - ping
      - envoy-v1-12-0
      - envoy-v1-12-1
      - envoy-v1-12-2
      - envoy-v1-12-3
      - envoy-v1-13-0
      - envoy-v1-13-1
      - envoy-v1-14-1
      - envoy-dev-latest
    working_dir: /go/github.com/socialpoint/envoyproxy-envoy-issues-9922/services/ping
    volumes:
      - ./services/ping:/go/github.com/socialpoint/envoyproxy-envoy-issues-9922/services/ping
    entrypoint: make test
